# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMDBMigrationManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FMDBMigrationManagerDemo
    pod 'FMDB', '~> 2.7.2'
    pod 'FMDBMigrationManager', '~> 1.4.1'

  target 'FMDBMigrationManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
